#!/usr/bin/env bash

image=ether-toolchain
br="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# Ask to build docker image if not found
if [[ ! $(docker image ls -q -f reference=${image}) ]]; then
  echo "Docker image does not exist. Do you want to build it?"
  read -r -p "[y/N]: " response
  case "$response" in
    [Yy][Ee][Ss]|[Yy])
      docker build -t ${image} ${br}/toolchain
      ;;
    *)
      exit
      ;;
  esac
fi

# Execute
if [[ $(docker ps -q -f name=${image}-run) ]]; then
  docker exec -it -u $(id -u):$(id -g) ${image}-run "$@"
else
  docker run -it --rm -v ${br}:/opt --name ${image}-run -u $(id -u):$(id -g) ${image} "$@"
fi
