#!/bin/bash -i

chmod 777 ./setup

etherpath="$(pwd)/ether"
echo "Ether paths is: $etherpath"

chmod 777 $etherpath
echo "Set exec rights"

if ln -f -s $etherpath /usr/local/bin/ether &> /dev/null; then
    echo "Added alias"
else
    echo "Cannot set alias. Try this script with sudo"
fi

echo $(whereis ether)

echo ""
echo "======="
echo "Use alias \"ether <subcommand>\""
echo "Press Ctrl+D to exit ether environment"
echo "======="

ether
