#!/bin/sh -e

if [ -z ${ISETHER+x} ]; then >&2 echo "Error! Unsupported environment"; exit 1; fi

iso=${BUILDROOT}/ether64.iso
${BUILDROOT}/toolchain/mkiso

qemu-system-x86_64 -s -S -cdrom ${iso} -curses
