#!/bin/sh -e

if [ -z ${ISETHER+x} ]; then >&2 echo "Error! Unsupported environment"; exit 1; fi

iso=${BUILDROOT}/ether64.iso
${BUILDROOT}/toolchain/mkiso

if [ "$1" == "debug" ]; then
    echo "Entering debug mode"
    qemu-system-x86_64 -s -S -cdrom ${iso} -display curses
else
    echo "Normal mode"
    qemu-system-x86_64 -s -cdrom ${iso} -display curses
fi
